### ISSUE TITLE
after rendering, index.html is blank.

### ISSUE THREAD

**Issue by spark-hydro** [datalorax/anderson-cv#3]
I started learning R because of your awesome cv. Running my R script generated the "index.html" file, but it's blank. Could you please help me with it?

**Comment by datalorax** [comment]
Hi - I see you have a fork of the repo. Is the fork itself not working? My CV is unfortunately not the most user-friendly. It has a lot of moving parts. I've been hoping to sort of package it up to make it easier for other to use but haven't gotten around to it yet.

**Comment by spark-hydro** [comment]
Thanks for your answer. The fork doesn't have an R script to render *.Rmd to *.html. So, I wrote a script to render it. Anyway, I am looking forward to using a sort of package.

**Comment by datalorax** [comment]
Yeah sorry that's definitely not clear. I render `anderson-cv.Rmd` to HTML then just rename it index.html so I can use GitHub Pages to publish it.

**Comment by spark-hydro** [comment]
Hi datalorax,

I discovered that when rendering the *.Rmd file to HTML, it generates additional folders and files. Your code works when the *.html file, along with all the additional folders and files, is passed to the GitHub Page. Thank you very much!

Seonggyu
